@startuml Container_Diagram_Full_Infrastructure
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(sre_engineer, "SRE инженер", "Мониторит и поддерживает систему")

System_Boundary(go_future_system, "GoFuture Platform") {
    
  ' ### ОСНОВНые МИКРОСЕРВИСЫ ###
   
 System_Boundary(api_gateway, "Новая микросервисаня архитектура") {
       
      Container(api_gateway_srv, "API Gateway", "Kong / Envoy / Traefik", "Маршрутизация, аутентификация, rate limiting и SSL-терминация")
     
       System_Boundary(booking_domain, "Booking Service") {
        Container(booking_srv, "Booking Service", "Django App", "Управление бронированиями")
        ContainerDb(booking_db, "Booking Database для тенанта 1", "PostgreSQL", "Данные бронирований для тенанта 1")
        ContainerDb(booking_db, "Booking Database для тенанта N", "PostgreSQL", "Данные бронирований для тенанта N")
    }

    System_Boundary(driver_domain, "Driver Service") {
        Container(driver_srv, "Driver Service", "Django App", "Управление водителями")
        ContainerDb(driver_db, "Driver Database для тенанта 1", "PostgreSQL", "Данные водителей для тенанта 1")
        ContainerDb(driver_db_n, "Driver Database для тенанта N", "PostgreSQL", "Данные водителей тенанта N")
    }

    System_Boundary(pricing_domain, "Pricing Service") {
        Container(pricing_srv, "Pricing Service", "Django App", "Ценообразование")
        ContainerDb(pricing_db, "Pricing Database для тенанта 1", "PostgreSQL", "Тарифы и правила для тенанта 1")
        ContainerDb(pricing_db_n, "Pricing Database для тенанта N", "PostgreSQL", "Тарифы и правила для тенанта N")
        ContainerDb(pricing_db_cache, "In-memory кеш для  pricing'а ", "Redis", "Кеширование данных")
        
    }

    System_Boundary(payments_domain, "Payments Service") {
        Container(payments_srv, "Payments Service", "Django App", "Платежи от пассажиров")
        ContainerDb(payments_db, "Payments Database для тенанта 1", "PostgreSQL", "Транзакции и чеки для тенанта 1")
        ContainerDb(payments_db_n, "Payments Database для тенанта N", "PostgreSQL", "Транзакции и чеки для тенанта N")

    }

    System_Boundary(payouts_domain, "Payouts Service") {
        Container(payouts_srv, "Payouts Service", "Django App", "Выплаты водителям")
        ContainerDb(payouts_db, "Payouts Database для тенанта 1", "PostgreSQL", "Данные балансов и выплат для тенанта 1")
        ContainerDb(payouts_db_n, "Payouts Database для тенанта N", "PostgreSQL", "Данные балансов и выплат для тенанта N")
    }

    System_Boundary(notification_domain, "Notification Service") {
        Container(notification_srv, "Notification Service", "Django App", "Управление уведомлениями")
        ContainerDb(notification_db, "Notification Database для тенанта 1", "PostgreSQL", "Шаблоны и очереди для тенанта 1")
        ContainerDb(notification_db_n, "Notification Database для тенанта N", "PostgreSQL", "Шаблоны и очереди для тенанта N")
        ContainerDb(notification_db_cache, "In-memory кеш для нотификаций", "Redis", "Кеширование данных")
    }

    System_Boundary(geography_domain, "Geography Service") {
        Container(geography_srv, "Geography Service", "Django App", "Геопоиск и маршрутизация")
        ContainerDb(geography_db, "Geography Database для тенанта 1", "PostgreSQL", "Пространственные данные для тенанта 1")
        ContainerDb(geography_db_n, "Geography Database для тенанта N", "PostgreSQL", "Пространственные данные для тенанта N")
        ContainerDb(geography_db_cache, "In-memory кеш для  geography", "Redis", "Кеширование данных")
    }

   
    System_Boundary(fraud_domain, "Fraud Service") {
        Container(fraud_srv, "Fraud Service", "Django App", "Обнаружение мошенничества")
        ContainerDb(fraud_db, "Fraud Database для тенанта 1", "PostgreSQL")
        ContainerDb(fraud_db_n, "Fraud Database для тенанта N", "PostgreSQL")
    }


     System_Boundary(analytics_domain, "Fraud Service") {
         Container(analytics_engine, "Analytics Engine", "Spark/Flink", "Обработка данных")
         ContainerDb(analytics_db, "Analytics DB", "ClickHouse", "Хранение аналитики")
      
    }
     
     Container(nginx, "nginx", "Маршрутизация внутри микросервисов")

    }

       
    ' ### ОЧЕРЕДИ И ВОРКЕРЫ ###
    
    ContainerQueue(mq_broker, "Брокер сообщений", "RabbitMQ", "Очередь для фоновых задач")
    Container(app_worker, "Воркеры фоновых задач", "Celery", "Обработка асинхронных задач")
    
    
    ' ### МОНИТОРИНГ И OBSERVABILITY ###
    Container(kafka_exporter, "Экспортер метрик Kafka для Prometheus", "Kafka Exporter")
    Container(monitoring, "Prometheus", "Monitoring System", "Сбор метрик и мониторинг")
    Container(grafana, "Grafana", "Dashboard System", "Визуализация метрик и дашборды")
    Container(loki, "Loki", "Log Aggregation", "Сбор и анализ логов")
    Container(alert_manager, "Alertmanager", "Alert System", "Управление алертами")
    
    
}







' ### МОНИТОРИНГ ###
Rel(booking_domain, monitoring, "▶ Отправляет метрики бронирований", "Prometheus Metrics")
Rel(payments_domain, monitoring, "▶ Отправляет метрики платежей", "Prometheus Metrics")
Rel(payouts_domain, monitoring, "▶ Отправляет метрики платежей", "Prometheus Me trics")
Rel(notification_tasks, monitoring, "▶ Отправляет метрики уведомлений", "Prometheus Metrics")
Rel(driver_domain, monitoring, "▶ Отправляет метрики сервиса водителей", "Prometheus Metrics")
Rel(pricing_domain, monitoring, "▶ Отправляет метрики сервиса ценообразования", "Prometheus Metrics")
Rel(geography_domain, monitoring, "▶ Отправляет метрики сервиса геопоиска", "Prometheus Metrics")
Rel(fraud_domain, monitoring, "▶ Отправляет метрики сервиса нарушений", "Prometheus Metrics")
Rel(app_worker, monitoring, "Отправляет метрики", "Prometheus Metrics")

Rel(mq_broker, kafka_exporter, "Метрики очередей", "Kafka Exporter")
Rel(kafka_exporter, monitoring, "Метрики очередей", "Kafka Exporter")

Rel(booking_db, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(payments_db, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(payout_db, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(driver_db, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(pricing_db, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(geography_db, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(analytics_engine, monitoring, "Метрики Spark/Flink", "PrometheusServlet")
Rel(analytics_db, monitoring, "Метрики Clickhouse", "Native support")
Rel(fraud_db, monitoring, "Метрики БД", "PostgreSQL Exporter")


Rel(monitoring, grafana, "Предоставляет данные", "PromQL")
Rel(monitoring, alert_manager, "Отправляет алерты", "Alert Rules")
Rel(alert_manager, sre_engineer, "Отправляет уведомления", "Email/Slack/Pager")
Rel(sre_engineer, grafana,"Визуальный контроль за метриками и дашбордами")

Rel(booking_domain, loki, "▶ логи бронирований", "Loki Logs")
Rel(payments_domain, loki, "▶ логи платежей", "Loki Logs")
Rel(notification_domain, loki, "▶ логи уведомлений", "Loki Logs")
Rel(notification_tasks, loki, "▶ логи уведомлений", "Loki Logs")
Rel(driver_domain, loki, "▶ логи сервиса водителей", "Loki Logs")
Rel(pricing_domain, loki, "▶ логи сервиса ценообразования", "Loki Logs")
Rel(geography_domain, loki, "▶ логи сервиса геопоиска", "Loki Logs")
Rel(fraud_domain, loki, "▶ логи сервиса нарушений", "Loki Logs")
Rel(app_worker, loki, "Отправляет логи", "Loki Logs")

Rel(api_gateway_srv, monitoring, "Метрики входящего\исходящего трафика")
Rel(nginx, monitoring, "Метрики трафика внутри платформы")

@enduml